### ISSUE TITLE
Aren't these the latent directions / pkl for stylegan1?

### ISSUE THREAD

**Issue by 8secz-johndpope** [AmarSaini/Epoching_StyleGan2_Setup#1]

**Comment by AmarSaini** [comment]
Thanks for the heads up! Just double checked and they're for stylegan2 :)

Source: https://twitter.com/robertluxemburg/status/1207087801344372736

![image](https://user-images.githubusercontent.com/25353789/91802052-74523380-ebdf-11ea-9b19-1c4835a7be7d.png)

**Comment by 8secz-johndpope** [comment]
true that. thanks
